package local:muswasm;

world muswasm {
  import startstream: func(kwargs: string) -> result<string, string>;
  import pollstream: func(qid: string) -> result<string, string>;
  import print: func(s: string) -> result<_, string>;
  import input: func() -> result<string, string>;
  export run: func(code: string) -> string;
}