package local:muswasm;

world muswasm {
  import startstream: func(llm: string, kwargs: string) -> result<string, string>;
  import pollstream: func(qid: string) -> result<string, string>;
  import print: func(s: string) -> result<_, string>;
  import input: func() -> result<string, string>;
  import runfunction: func(name: string, inputs: string) -> result<string, string>;
  export run: func(code: string, llms: list<string>, tools: string, functions: list<string>) -> string;
}