name: Main push / PR

on:
  push:
    branches: [ main ]


concurrency:
  group: main
  cancel-in-progress: true



jobs:
  test:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    uses: ./.github/workflows/run-tests-job.yml
  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.23.0
        with:
          github_token: ${{ secrets.PAT }}

  #release:
  #  permissions: 
  #      contents: 'write'
  #  uses: ./.github/workflows/release-latest.yml
      