name: Release latest

on:
  push:
    tags:
      - 'v*'
  
  
jobs:
  release_latest:
    permissions:
      contents: write
    name: Release latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
            python -m pip install uv
            echo "$HOME/.local/bin" >> $GITHUB_PATH
              
      - name: Install Dependencies
        run: uv sync --all-extras
    
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get current version
        run: echo "CURRENT_VERSION=$(uv run scripts/get_version.py pyproject.toml)" >> $GITHUB_ENV
      
      - name: Build project
        run: uv build

      - name: Release
        run: |
          gh release create v${{ env.CURRENT_VERSION }} ./dist/mus*.whl --title "Release v${{ env.CURRENT_VERSION }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      