name: Release latest

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release_latest:
    name: Release latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
            
      - name: Install Dependencies
        run: poetry install --no-interaction --no-root
    
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Get current version
        run: echo "CURRENT_VERSION=$(poetry version -s)" >> $GITHUB_ENV
      
      - name: Build project
        run: poetry build

      - name: Update latest tag
        run: |
          git tag -f latest
          git push origin latest --force
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/mus*.whl

      