name: Run Python Tests

on:
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        python -m pip install uv
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install Dependencies
      run: uv sync --all-extras
    
    - name: Run pyright
      run: uv run pyright

    - name: Run tests
      run: uv run pytest --md-report --md-report-verbose 1 --md-report-output md-report.md --cov-report xml
    
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: markdown
        output: both
        badge: true
    
    - name: Add summary
      run: |
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY 
        cat md-report.md >> $GITHUB_STEP_SUMMARY
      

