name: Run Python Tests

on:
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true
    
    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install --all-extras --no-interaction --no-root
    
    - name: Run tests
      run: poetry run python -m pytest --md-report --md-report-verbose 1 --md-report-output md-report.md --cov-report xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        format: markdown
        output: both
        badge: true
    
    - name: Add summary
      run: |
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY 
        cat md-report.md >> $GITHUB_STEP_SUMMARY
      

